#!/usr/bin/env bash

words=$(grep d /usr/share/dict/words)

words_length=$(grep -c d /usr/share/dict/words)

i=0
for word in $words; do
	((i++))
done

echo $words_length
echo $i

i=0
while read -r word; do
	((i++))
done <<< "$words"
echo $i

i=0
grep d /usr/share/dict/words | while read -r word; do
	((i++))
done
echo $i # new subprocess

i=0
while read -r word; do
	((i++))
done < <(grep d /usr/share/dict/words)
echo $i # streaming
